### ISSUE TITLE
.getTotalLength is not a function

### ISSUE THREAD

**Issue by KutnerUri** [Eliav2/react-xarrows#110]
getting this error during tests:
(Seems to be related to #72)

```
TypeError: _c.getTotalLength is not a function

...
      at Object.getPosition (node_modules/.pnpm/registry.npmjs.org+react-xarrows@2.0.2_react@16.13.1/node_modules/react-xarrows/lib/index.js:1124:90)
      at node_modules/.pnpm/registry.npmjs.org+react-xarrows@2.0.2_react@16.13.1/node_modules/react-xarrows/lib/index.js:180:37
      at commitHookEffectListMount (node_modules/.pnpm/registry.npmjs.org+react-dom@16.13.1_react@16.13.1/node_modules/react-dom/cjs/react-dom.development.js:19731:26)
```

version: 2.0.2
using Jest and react testing library.

**Comment by DiaconuDan** [comment]
Hey @KutnerUri ,

Any updates on this ? I am also experiencing it

**Comment by DiaconuDan** [comment]
Meanwhile, I did not figured out the fix but did a workaround by enabling XArrows only when I'm not in jest enviroment.
  {process.env.JEST_WORKER_ID === undefined && <ComponentWitnXarrow > }

**Comment by JoshK2** [comment]
Any update on this?

**Comment by robertpin** [comment]
I get the same error using Jest and React testing library with TypeScript. Any updates?

**Comment by maxPiroddi** [comment]
Seems to still be no updates on this one...

For the time being, I have been working around it similar to [DiaconuDan](https://github.com/DiaconuDan)

`{process.env.NODE_ENV !== 'test' && <Xarrow ... />`

But definitely not an ideal solution!

**Comment by robertpin** [comment]
I was able to bypass it by mocking the component (I prefer not to conditionally render it based on the NODE_ENV).

```
jest.mock('react-xarrows', () => {
  return {
    __esModule: true,
    default: () => <span />,
    useXarrow: () => null,
  };
});
```
